services:
    jenkins:
        container_name: jenkins
        build: jenkins-config
        image: jenkins
        ports:
            - 8080:8080
            - 50000:50000
        networks:
            - bridge
        environment: 
          - JENKINS_ADMIN_ID=admin  
          - CASC_JENKINS_CONFIG=/var/jenkins_home/cask.yaml
        volumes:
          - jenkins_home:/var/jenkins_home
          - ./jenkins-config/casc.yaml:/var/jenkins_home/cask.yaml
        secrets:
          - JENKINS_ADMIN_PASSWORD

    agent:
        container_name: agent
        build: agent
        image: agent
        ports:
            - "8081:8081"
        networks:
            - bridge

secrets:
  JENKINS_ADMIN_PASSWORD:
    file: /Users/kbogdanski/jenkins_home/JENKINS_ADMIN_PASSWORD
networks:
    bridge: {}
volumes:
  jenkins_home: