jenkins:
  systemMessage: "Controlled by Configuration as Code by przemo1337"

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

jobs:
  - file: "/usr/local/jobs/seedjob.groovy"
  - file: "/usr/local/jobs/pipeline.groovy"

unclassified:
  location:
    url: "http://server_ip:8080/"